language: php
dist: trusty
sudo: required
php:
  - '7.2'
  - '7.3'
before_script:
  - composer install
script:
  - php -v
  - phpunit --version
  - vendor/bin/codecept --version
  - vendor/bin/codecept run unit
